### ISSUE TITLE
Dataset of the code

### ISSUE THREAD

**Issue by Mehralian** [a-mustafa/Novel-Class-Detection#1]
I've tried to run the code using _arff_ version of MNIST and KDDCup99 (seen in some comments of the code) but the code threw following exceptions. Would you please specify the data-set for which the code works?

Exception stack trace:
`java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at java.io.BufferedWriter.flush(BufferedWriter.java:254)
	at reasc.Autoencoder.pipe(Autoencoder.java:60)
	at reasc.Autoencoder.TrainAndTransform(Autoencoder.java:93)
	at mineClass.Miner.Classify(Miner.java:1250)
	at mineClass.Miner.main(Miner.java:2207)`

`empty String
Exception in thread "main" java.lang.NullPointerException
	at mineClass.Miner.Classify(Miner.java:1282)
	at mineClass.Miner.main(Miner.java:2207)`

**Comment by Mehralian** [comment]
@a-mustafa
